### ISSUE TITLE
How do you specify a ResourceOverride to target a specific member cluster?

### ISSUE THREAD

**Issue by tillig** [Azure/fleet#1146]
I'm trying to set up a `ResourceOverride` that will allow targeting a specific cluster with a specific override. The idea is that certain services need to know the name of the member cluster as part of their functioning, so patching in the member cluster name is the key.

When you use Terraform or the API to create a `MemberCluster`, you don't have the option of adding labels. That means if you add them post-deploy, managing things through Terraform or the API will see the labels as drift.

A provisioned `MemberCluster` currently looks like this:

```yaml
apiVersion: cluster.kubernetes-fleet.io/v1
kind: MemberCluster
metadata:
  annotations:
    fleet.azure.com/cluster-resource-id: /subscriptions/<subscription-guid>/resourceGroups/my-rg/providers/Microsoft.ContainerService/managedClusters/workload-0
  labels:
    fleet.azure.com/location: westcentralus
    fleet.azure.com/resource-group: my-rg
    fleet.azure.com/subscription-id: <subscription-guid>
  name: workload-0
spec:
  heartbeatPeriodSeconds: 15
  identity:
    kind: User
    name: <user-guid>
```

Note there is no label there with the name of the cluster. That makes sense, as the name is... the `name`.

I can create a `ResourceOverride` like this:

```yaml
apiVersion: placement.kubernetes-fleet.io/v1alpha1
kind: ResourceOverride
metadata:
  name: resource-override
  namespace: my-ns
spec:
  policy:
    overrideRules:
    - clusterSelector:
        clusterSelectorTerms:
        - labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - workload-0
      jsonPatchOverrides:
      - op: replace
        path: /data/K8S_CLUSTER
        value: workload-0
      overrideType: JSONPatch
    - clusterSelector:
        clusterSelectorTerms:
        - labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - workload-1
      jsonPatchOverrides:
      - op: replace
        path: /data/K8S_CLUSTER
        value: workload-1
      overrideType: JSONPatch
  resourceSelectors:
  - group: ""
    kind: ConfigMap
    name: settings
    version: v1
```

Here's the gotcha: **The `clustrerSelectorTerms` doesn't support `propertySelector` even though it's in the CRD.** That means I can't say `propertySelector` and select `name` as the property on the cluster - I can _only_ use `labelSelector`.

So my options, from what I can tell, are:

- Don't patch things for individual workload clusters like this.
- Only put one workload cluster in each location or resource group such that one of the other `label` values is unique.
- Patch the `labels` on the `MemberCluster` after deploying and remember every time I update anything with Terraform or the API that I may need to go back and re-update the `labels` on the `MemberCluster` entities.

Am I missing something fundamental?
