### ISSUE TITLE
Enable Hub to take over "unmanaged resources" in member cluster

### ISSUE THREAD

**Issue by tom-data** [Azure/fleet#360]
There is a use case where namespaces have been created and workloads have been deployed to a cluster. Then this cluster joins the multicluster. In this case, we need to create namespace, namespace scoped resources and CRPs in the Hub. However, when work object is pulled by the work controller in the member cluster, the owner reference check fails in the function isManifestManagedByWork(). We want the work controller to treat this case as Hub taking over previously "unmanaged resources". The work controller shall create appliedWork for this resource and updated CRP status as in the case of successful creation of a new resource (propagated down from Hub) in the member cluster..

**Comment by implodingduck** [comment]
I was messing around with a similar thing, where I had existing namespaces and tried to get them into the fleet,

Getting the appliedwork object on the member cluster has a uid which you can add to existing resources for the ownerReferences...

Sample appliedwork from `kubectl get appliedwork hello-world -oyaml`

```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: AppliedWork
metadata:
  creationTimestamp: "2023-07-20T15:39:16Z"
  generation: 1
  name: hello-world
  resourceVersion: "31516"
  uid: ########-####-####-####-1313c541705b
```

Then I updated my namespace with the following ownerReferences metadata add last-applied-configuration annotation:
```
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  ownerReferences:
  - apiVersion: multicluster.x-k8s.io/v1alpha1
    blockOwnerDeletion: false
    kind: AppliedWork
    name: hello-world
    uid: ########-####-####-####-1313c541705b
  annotations:
    fleet.azure.com/last-applied-configuration: '{}'
```

After a minute or two I was getting proper values for things from the Fleet hub... 

I hope that can help with your use case!
