### ISSUE TITLE
[BUG] Jobs can't be propagate to member clusters

### ISSUE THREAD

**Issue by nikawang** [Azure/fleet#456]
### **Describe the bug**
During my testing, I encountered an error when Fleet Manager tried to distribute Jobs to Member Clusters as below:
```
message: 'Failed to apply manifest: Job.batch 'hello-world-job' is invalid:
          [spec.template.metadata.labels[controller-uid]: Invalid value: map[string]string{'controller-uid':'91cb485c-9966-401a-b68e-2a1d3ffc1c98',
          'job-name':'hello-world-job'}: must be ''f81acbaf-b289-465d-923f-f022f6cf77bf'',
          spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{'controller-uid':'91cb485c-9966-401a-b68e-2a1d3ffc1c98'},
          MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]'
        reason: appliedManifestFailed
        status: 'False'
```

### **Environment**
Please provide the following: 
- Hub cluster details
- Member cluster details

### **To Reproduce**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  completions: 20
  parallelism: 5
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command: ["sh", "-c", "echo 'Hello, World!'"]
      restartPolicy: Never
```

### **Expected behavior**
Should see the job in the member clusters
