### ISSUE TITLE
[feature] adopt cluster inventory API from k8s-sig multi-cluster

### ISSUE THREAD

**Issue by zhiying-lin** [Azure/fleet#467]
The community is discussing a unified [Cluster Inventory API](https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/edit?pli=1) for cluster registry info.

The spec likes below:
```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ClusterInventory
metadata:
 name: some-cluster
spec:
 accessObjectRefs: # optional object points to the resource that declares how to access the cluster
 - group: someGroup
   resource: someResource
   name: someName
   namespace: someNamespace
   type: KUBECONFIG
 taints:
   - key: key1
     value: value1
     effect: NoSchedule
     addTime: xxx
 healthinessProbe:
   heartbeatIntervalSeconds: 60
status:
 version:
   kubernetes: 1.26.1
 resources: # total resources of a cluster
   capacity:
     cpu: 12
     memory: 12Gi
   allocatable:
     cpu: 10
     memory: 16Gi
 properties:
   - name: clusterset.k8s.io
     value: some-clusterset
 conditions:
   - type: Healthy
     status: True
     lastTransitionTime: "2023-05-08T07:58:55Z"
     message: ""
```
It‘s similar to our [membercluster object](https://github.com/Azure/fleet/blob/main/apis/v1alpha1/membercluster_types.go#L21).

Once the community has an unified API, fleet can migrate to it and benefit from that. So that we can easily integrate with other multi-cluster projects, such as KubeVela, argoWorkflow and argoCD.
